<table>
    <thead>
        <tr>
							<th>no_sku</th>
							<th>reff</th>
							<th>destination</th>
							<th>vendor</th>
							<th>category</th>
							<th>week</th>
                            <th>type_week</th>
							<th>shipment_type</th>
							<th>origin</th>
							<th>volume</th>
							<th>total_quantity</th>
							<th>ft40</th>
							<th>ft20</th>
							<th>lcl_af</th>
							<th>stuffing_place</th>
							<th>stuffing_date</th>
							<th>no_invoice</th>
							<th>bl_number</th>
							<th>shipping_line</th>
							<th>vesel</th>
							<th>etd</th>
							<th>eta</th>
	
        </tr>
    </thead>
</table>